### ISSUE TITLE
Void Motor not working across dimensions

### ISSUE THREAD

**Issue by Flintley** [Duqueeee/create-utilities#13]
When I try to transfer kinetic energy from the overworld to the nether nothings happens. The frequencies are the same.

**Comment by Duqueeee** [comment]
It is behaving as expected. Unfortunatly, Create relies too heavily on a kinetic network being one single dimension. Changing that would be too unstable and cause alot of unforeseen problems, specially with other addons. I apologise for the inconvenience.

**Comment by Flintley** [comment]
All good!
