### ISSUE TITLE
Void motor can't work across dimensions

### ISSUE THREAD

**Issue by in1t1a1** [Duqueeee/create-utilities#15]
Version: createutilities-0.1.4+1.20.1 Forge
The void chest and void tank can work across dimensions

**Comment by Duqueeee** [comment]
It is behaving as expected. Unfortunatly, Create relies too heavily on a kinetic network being one single dimension. Changing that would be too unstable and cause alot of unforeseen problems, specially with other addons. I apologise for the inconvenience.
