### ISSUE TITLE
Lava source becomes cobblestone

### ISSUE THREAD

**Issue by Flintley** [Duqueeee/create-utilities#17]
I set up a lava farm in the Nether (via bottomless supply) and chunkloeded it. When i now try to place lava from the void tank it turn to cobllestone after 0.5 sec. That doesn't make sense to me...

**Comment by Duqueeee** [comment]
I'm unable to replicate the issue. Are you sure it is caused by Create Utilities?

**Comment by Flintley** [comment]
Yes, im pretty sure. It seems there was water in the pipes but after replacing them it still didnt work.

**Comment by Duqueeee** [comment]
Is it still happening?

**Comment by Flintley** [comment]
I don't know, I didn't play my ModPack since 3 months. You can close this issue for now, when I encounter this again I can reopen it.
