### ISSUE TITLE
Void Chests on Contraptions Issue

### ISSUE THREAD

**Issue by GentlemanCheesy** [Duqueeee/create-utilities#19]
Void Chests on Contraptions seem to stop picking up items after a server restart. This has happened multiple times upon rejoining the next day after it was working fine. Stopping the contraption and starting it again fixes the issue. Chunk loaders are present from another mod so im unsure if its something todo with how the chunk loaders function with restarts?

Using Neoforged 1.20.1
Create 0.5.1f and Utilities 0.1.4

Chunk loader mod:
https://www.curseforge.com/minecraft/mc-mods/chunk-loaders

**Comment by Duqueeee** [comment]
Hi! Thank you for bringing this issue to my attention! The issue has been fixed in the latest version of the mod!
Check it out at:
**CurseForge:** https://www.curseforge.com/minecraft/mc-mods/createutilities
**Modrinth:** https://modrinth.com/mod/create-utilities
