### ISSUE TITLE
*QUESTION* Interdimensional stress transport?

### ISSUE THREAD

**Issue by JuniorWolfgamingDE** [Duqueeee/create-utilities#2]
Hey, just a question - no issue. Do you plan on adding interdimensional support for the void motor and co.?

**Comment by Duqueeee** [comment]
Hi! Thank you for your question! Yes, I do intend on doing so soon!

**Comment by Duqueeee** [comment]
Hello again,

After thoroughly studying Create's code and attempting to implement interdimensional stress transfer, I have come to the unfortunate realization that it is not a viable option. The code heavily relies on a kinetic network functioning within a single dimension, making it extremely unstable to introduce such a feature. Doing so could result in unforeseen issues within Create as well as other add-ons.

Therefore, I regretfully inform you that interdimensional stress transfer will not be added in the foreseeable future.
