### ISSUE TITLE
void motor causing game to be stuck on saving world

### ISSUE THREAD

**Issue by qwek1** [Duqueeee/create-utilities#20]
In my modpack, https://www.curseforge.com/minecraft/modpacks/aoc (v1.9.7) if you place down a void motor and leave the game, the game will get stuck on saving world. The modpack uses the latest version of both Create, and Create Utilities

**Comment by Xenxia** [comment]
Hello, I have the same problem with my server, the logs remain blocked on saving world and my processor is used at 50% continuously.

Forge version: 43.3.5
Minecraft version: 1.19.2
Mod version: 0.1.4

**Comment by Duqueeee** [comment]
Hi! Thank you for bringing this issue to my attention! The issue has been fixed in the latest version of the mod!
Check it out at:
**CurseForge:** https://www.curseforge.com/minecraft/mc-mods/createutilities
**Modrinth:** https://modrinth.com/mod/create-utilities
