### ISSUE TITLE
Connected Texture missing

### ISSUE THREAD

**Issue by mlus-asuka** [Duqueeee/create-utilities#21]
like this 
![image](https://github.com/Duqueeee/create-utilities/assets/80941936/2a0d8aba-8770-4c1e-b030-9c9a28b73be4)

**Comment by Duqueeee** [comment]
Hi! Thank you for bringing this issue to my attention! The issue has been fixed in the latest version of the mod!
Check it out at:
**CurseForge:** https://www.curseforge.com/minecraft/mc-mods/createutilities
**Modrinth:** https://modrinth.com/mod/create-utilities
