### ISSUE TITLE
[Feature Request]: Ponder menu

### ISSUE THREAD

**Issue by steve-the-player** [Duqueeee/create-utilities#22]
The mod currently doesn't implement Create's "Ponder" feature (those little scenes that tell you how things work), which would be a nice addition to the mod. I believe there is a mod that helps make them.

**Comment by Duqueeee** [comment]
Hi! Thank you for the suggestion! The feature was added in the latest version of the mod!
Check it out at:
**CurseForge:** https://www.curseforge.com/minecraft/mc-mods/createutilities
**Modrinth:** https://modrinth.com/mod/create-utilities
