### ISSUE TITLE
0.2.0 Crashes on startup

### ISSUE THREAD

**Issue by Pantheris2019** [Duqueeee/create-utilities#23]
I start up the game, but each of the times I start it up, I get this.
![image](https://github.com/Duqueeee/create-utilities/assets/84039461/79b7264a-72e8-41c7-9b88-6b1677d439e7)

**Comment by rohanverma2007** [comment]
Same issue here, I've linked the crash report

Crash report
[crash-2024-02-09_16.43.01-fml.txt](https://github.com/Duqueeee/create-utilities/files/14221798/crash-2024-02-09_16.43.01-fml.txt)

**Comment by Duqueeee** [comment]
It seems I am unable to replicate this issue. Could you give me the list of mods you are currently using (and their versions aswell)?

**Comment by Duqueeee** [comment]
I came up with a potential fix, but since I can't replicate the issue, I'm unable to test it. Could you try it out and let me know if the crash still persists?
[createutilities-0.2.0+1.20.1.zip](https://github.com/Duqueeee/create-utilities/files/14223445/createutilities-0.2.0%2B1.20.1.zip)

**Comment by Pantheris2019** [comment]
I am running 1.19.2 because I am planning on running a server.

**Comment by Duqueeee** [comment]
Alright, try this version then.
[createutilities-0.2.0+1.19.2.zip](https://github.com/Duqueeee/create-utilities/files/14223882/createutilities-0.2.0%2B1.19.2.zip)

**Comment by Pantheris2019** [comment]
That's the one **I am having issues with.**

**Comment by Duqueeee** [comment]
I made some changes that might fix your problem. Could you try it out and let me know if the issue still persists?

**Comment by rohanverma2007** [comment]
I experience the same issue on 1.20.1, is there any fix file for that by any chance?

**Comment by Duqueeee** [comment]
Try out this version and let me know if it's solved:
[createutilities-0.2.0+1.20.1.zip](https://github.com/Duqueeee/create-utilities/files/14223445/createutilities-0.2.0%2B1.20.1.zip)

**Comment by rohanverma2007** [comment]
Thank you! It's fixed now

**Comment by Duqueeee** [comment]
Great! I'm happy to hear it!
