### ISSUE TITLE
void battery uses wrong tag for copper plates/gold nuggets (1.19.2) (Forge)

### ISSUE THREAD

**Issue by Gitcrafter** [Duqueeee/create-utilities#25]
the void battery uses the wrong tags for the copper plates(see screenshot 1) and gold nuggets(see screenshot 2) in its recipe, the correct tag for copper plates is "forge:plates/copper" and for gold nuggets is "forge:nuggets/gold", please fix this

you should also check the other modfiles for other minecraft versions if they have the same issue
create utilities version: 1.19.2 0.2.0

![2024-02-09_16 02 31](https://github.com/Duqueeee/create-utilities/assets/81863925/9771934d-b987-476f-97fb-371e942ad299)
![2024-02-09_16 10 30](https://github.com/Duqueeee/create-utilities/assets/81863925/80067f8d-0dac-4950-a8a5-f02064eb67ca)

**Comment by Gitcrafter** [comment]
also another issue, why is the transferrate of the void batteries so absolutely pitifull

**Comment by Duqueeee** [comment]
Oh my bad, I forgot to change it when I ported the changes from Fabric to Forge. I'll fix it right away.
As for the transferrate, what do you feel is a more suitable value?

**Comment by Gitcrafter** [comment]
thanks for the quick reply, as for the transferrate I would say 4096, because that is the default transferrate of create crafts and additions large wire connector

**Comment by Duqueeee** [comment]
Alright, thank you! I'll use that value and reupload the files in a moment. I'll let you know when I do.

**Comment by Gitcrafter** [comment]
thank you

**Comment by Gitcrafter** [comment]
thank you again for uploading the fixed version

**Comment by Duqueeee** [comment]
Oh, I was gonna warn you now xD
Thank you for the help! I really appreciate it!

**Comment by Gitcrafter** [comment]
Thank you for the nice words
