### ISSUE TITLE
Forge 1.18.2 0.2.0 Crash on startup, requires create 0.5.1.f-332 with create 0.5.1.f present

### ISSUE THREAD

**Issue by antdoesthings** [Duqueeee/create-utilities#26]
This happens on startup. I'm guessing it'll be fixed soon considering you already removed the version from curseforge but yea. I did also report this on the discord so ye.
[crash-report.txt](https://github.com/Duqueeee/create-utilities/files/14228210/message.txt)

**Comment by antdoesthings** [comment]
The latest modrinth 1.18.2 forge version of the mod that was recently added (like 2 hours ago) didn't have this error! Just the removed curseforge one did. I'll be marking this as finished now :)

**Comment by Aeonsteel** [comment]
This issue has returned for the latest version of Create utilities on 1.18, on both Curseforge and Modrinth. Please fix.
