### ISSUE TITLE
Placing Void Tank in Fabric causes crash and prevents login

### ISSUE THREAD

**Issue by kj4lxc** [Duqueeee/create-utilities#29]
Basically what it says on the tin.

Steps to reproduce.

1. Place void tank
2. crash
3. profit???

Fully unsure if it is fully your thing or not due to the crash log stating the problem is relating to Create itself or more so, the porting lib.

Mod works flawlessly on Forge 1.20.1 but on this fabric pack it has this issue, which bums me out because now I cant set up my boilers yet :(

Find the log attached.  For full mod list, I am using this pack here: https://legacy.curseforge.com/minecraft/modpacks/cstmgames-creative-tendencies

[crash-2024-03-24_23.44.59-client.txt](https://github.com/Duqueeee/create-utilities/files/14738551/crash-2024-03-24_23.44.59-client.txt)

Thanks in advance!

**Comment by Duqueeee** [comment]
Hi! Thank you for bringing this issue to my attention.
The problem should be fixed in the latest version of the mod!
Download it here:
**CurseForge:** https://www.curseforge.com/minecraft/mc-mods/createutilities/files/5212825
**Modrinth:** https://modrinth.com/mod/create-utilities/version/p90nqzkX
