### ISSUE TITLE
Mod needs an update to the latest build of Create

### ISSUE THREAD

**Issue by Sunconure11** [Duqueeee/create-utilities#3]
https://gist.github.com/Sunconure11/eead680fabe990b6cde919226df76d52

**Comment by Duqueeee** [comment]
Thank you for bringing this to my attention!

The lastest version of the mod can be found at:
**CurseForge**: https://www.curseforge.com/minecraft/mc-mods/create-utilities-fabric/files/4626478
**Modrinth**: https://modrinth.com/mod/create-utilities/version/Wk9F01qV
