### ISSUE TITLE
Like in #26 , 1.18.2's version 0.2.0 requires a non-existent version of Create.

### ISSUE THREAD

**Issue by Aeonsteel** [Duqueeee/create-utilities#31]
Title. #26

**Comment by Duqueeee** [comment]
Hi! The issue should be fixed in the latest release.
You can find it in:
**Curseforge:** https://www.curseforge.com/minecraft/mc-mods/createutilities/files/5228626
**Modrinth:** https://modrinth.com/mod/create-utilities/version/kV99Qqsh
