### ISSUE TITLE
can you update a mod to 0.5.1-c?

### ISSUE THREAD

**Issue by MisileLab** [Duqueeee/create-utilities#4]

**Comment by Sunconure11** [comment]
Can confirm this is also a problem.

**Comment by Sunconure11** [comment]
@Duqueeee

**Comment by Duqueeee** [comment]
Hello!

The mod has been updated to Create's version 0.5.1-c-build.1160+mc1.19.2.
You can download it in the following links:
**Curseforge:** https://www.curseforge.com/minecraft/mc-mods/create-utilities-fabric/files/4722043
**Modrinth:** https://modrinth.com/mod/create-utilities/version/0.1.3+1.19.2
