### ISSUE TITLE
Game crashes when attempting to start

### ISSUE THREAD

**Issue by YukiRainee** [Duqueeee/create-utilities#9]
List of mods should be in the logs as well 

https://mclo.gs/wa8vQAW

**Comment by HockeyZman2000** [comment]
I think it's due to Create's most recent update. You'll have to wait for Duqueeee to update the mod in order for it to work properly.

**Comment by Duqueeee** [comment]
Like [HockeyZman2000](https://github.com/HockeyZman2000) said, the issue seems to be caused by Create's most recent version. Fortunately, the mod has been updated today and as such this issue should be fixed.
